// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnswerOptionWithQuestionForeginKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnswerOptionWithQuestionForeginKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202111120900192_AnswerOptionWithQuestionForeginKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
