// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mcqquestion_subject_topic_chapter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mcqquestion_subject_topic_chapter));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261623039_mcqquestion_subject_topic_chapter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
