// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class studentId_in_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentId_in_User));
        
        string IMigrationMetadata.Id
        {
            get { return "202110311625238_studentId_in_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
