// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class topicname_changed_from_int_to_str : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topicname_changed_from_int_to_str));
        
        string IMigrationMetadata.Id
        {
            get { return "202110301729124_topicname_changed_from_int_to_str"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
