// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class batch_tbl_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(batch_tbl_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202112020602316_batch_tbl_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
